sudo: required
services:
    - docker

before_install:
    - docker build -t crberme/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true crberme/react-test npm test

after_success:
    - docker build -t crberme/complex-client ./client
    - docker build -t crberme/complex-server ./server
    - docker build -t crberme/complex-nginx ./nginx
    - docker build -t crberme/complex-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push crberme/complex-client
    - docker push crberme/complex-server
    - docker push crberme/complex-nginx
    - docker push crberme/complex-worker