version: "3"
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
        restart: always
    redis:
        image: redis:latest
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PGUSER=${PGUSER}
            - PGHOST=${PGHOST}
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGPORT=${PGPORT}
        depends_on: 
            - postgres
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports: 
            - "3050:80"
        depends_on: 
            - api
            - client